services:
  sftp:
    build:
      context: .
    container_name: sftp-server
    ports:
      - "2222:22"
    environment:
      - SFTP_USER=david
      - SFTP_PASS=12345
      - USER_UID=1000  # Automatically maps to your laptop user ID
      - USER_GID=1000  # Automatically maps to your laptop group ID
    volumes:
      - ./data:/sftp/files
    restart: unless-stopped
